In [0]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [0]:
from google.colab import drive
drive.mount("/content/drive")

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
project_path = "/content/drive/My Drive/AIML/NeuralNet/"

In [0]:
df = pd.read_csv(project_path + "bank.csv")

In [0]:
df.shape

(10000, 14)

In [0]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [0]:
df = df.drop(['CustomerId','RowNumber','Surname'],axis=1)

In [0]:
X=df.drop("Exited",axis=1)

In [0]:
X.shape

(10000, 10)

In [0]:
Y=df[['Exited']]

In [0]:
Y.shape

(10000, 1)

In [0]:
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
X.loc[:, 'Geography'] = labelencoder_x.fit_transform(X.loc[:, 'Geography'])
X.loc[:, 'Gender'] = labelencoder_x.fit_transform(X.loc[:, 'Gender'])
X.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [0]:
from keras.utils import to_categorical
encoded = pd.DataFrame(to_categorical(X.loc[:, 'Geography']))
X = pd.concat([encoded, X], axis = 1)
X.head()

0    1    2  CreditScore  Geography  Gender  Age  Tenure    Balance  \
0  1.0  0.0  0.0          619          0       0   42       2       0.00   
1  0.0  0.0  1.0          608          2       0   41       1   83807.86   
2  1.0  0.0  0.0          502          0       0   42       8  159660.80   
3  1.0  0.0  0.0          699          0       0   39       1       0.00   
4  0.0  0.0  1.0          850          2       0   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0              1          1               1        101348.88  
1              1          0               1        112542.58  
2              3          1               0        113931.57  
3              2          0               0         93826.63  
4              1          1               1         79084.10

In [0]:
X=X.drop(['Geography',0],axis=1)

In [0]:
X.head()

1    2  CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  \
0  0.0  0.0          619       0   42       2       0.00              1   
1  0.0  1.0          608       0   41       1   83807.86              1   
2  0.0  0.0          502       0   42       8  159660.80              3   
3  0.0  0.0          699       0   39       1       0.00              2   
4  0.0  1.0          850       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [0]:
X.shape

(10000, 11)

In [0]:
from scipy import stats
from scipy.stats import zscore
X.apply(zscore)

1         2  CreditScore    Gender       Age    Tenure   Balance  \
0    -0.578736 -0.573809    -0.326221 -1.095988  0.293517 -1.041760 -1.225848   
1    -0.578736  1.742740    -0.440036 -1.095988  0.198164 -1.387538  0.117350   
2    -0.578736 -0.573809    -1.536794 -1.095988  0.293517  1.032908  1.333053   
3    -0.578736 -0.573809     0.501521 -1.095988  0.007457 -1.387538 -1.225848   
4    -0.578736  1.742740     2.063884 -1.095988  0.388871 -1.041760  0.785728   
5    -0.578736  1.742740    -0.057205  0.912419  0.484225  1.032908  0.597329   
6    -0.578736 -0.573809     1.774174  0.912419  1.056346  0.687130 -1.225848   
7     1.727904 -0.573809    -2.840488 -1.095988 -0.946079 -0.350204  0.618019   
8    -0.578736 -0.573809    -1.547141  0.912419  0.484225 -0.350204  1.050820   
9    -0.578736 -0.573809     0.346319  0.912419 -1.136786 -1.041760  0.931463   
10   -0.578736 -0.573809    -1.267778  0.912419 -0.755372  0.341352  0.409185   
11   -0.578736  1.742740    -1.588528  0.912419 -1.422847 -0.695982 -1.225848   
12   -0.578736 -0.573809    -1.805810 -1.095988 -0.469311  1.724464 -1.225848   
13   -0.578736 -0.573809    -1.050496 -1.095988 -1.327494 -0.004426 -1.225848   
14   -0.578736  1.742740    -0.160673 -1.095988 -0.373958  0.687130 -1.225848   
15    1.727904 -0.573809    -0.357262  0.912419  0.579578 -0.695982  1.068103   
16    1.727904 -0.573809     0.025569  0.912419  1.819175 -1.387538  0.899393   
17   -0.578736  1.742740    -1.050496 -1.095988 -1.422847  1.378686 -1.225848   
18   -0.578736  1.742740    -0.657318  0.912419  0.579578  0.341352 -1.225848   
19   -0.578736 -0.573809     0.780884 -1.095988 -1.422847  0.341352 -1.225848   
20   -0.578736 -0.573809     0.842964  0.912419  0.198164  1.032908 -1.225848   
21   -0.578736  1.742740    -0.150326 -1.095988 -0.660018  1.032908 -1.225848   
22   -0.578736  1.742740    -1.454020 -1.095988 -0.087897 -0.350204 -1.225848   
23   -0.578736 -0.573809     0.191117  0.912419  0.674932 -0.695982 -1.225848   
24   -0.578736 -0.573809     2.022497 -1.095988 -0.087897 -0.004426 -1.225848   
25   -0.578736 -0.573809    -0.760786  0.912419 -1.327494 -0.695982 -1.225848   
26    1.727904 -0.573809     1.091287  0.912419 -0.278604 -1.041760  0.966911   
27   -0.578736 -0.573809    -0.822867  0.912419  0.484225  1.378686 -1.225848   
28    1.727904 -0.573809    -0.791826 -1.095988  0.388871 -0.695982  1.039575   
29   -0.578736 -0.573809    -2.478351  0.912419 -0.946079 -1.733315 -0.269075   
...        ...       ...          ...       ...       ...       ...       ...   
9970 -0.578736 -0.573809    -1.371246  0.912419  0.293517  0.687130  1.194679   
9971 -0.578736 -0.573809     1.887989 -1.095988 -0.469311 -0.695982  1.094105   
9972 -0.578736 -0.573809     1.111980  0.912419 -1.232140 -0.350204  1.270210   
9973 -0.578736 -0.573809    -0.408996  0.912419 -1.136786  0.687130 -1.225848   
9974 -0.578736 -0.573809    -0.698705  0.912419 -0.564665  0.687130  0.737984   
9975  1.727904 -0.573809    -0.419342  0.912419  1.056346 -1.387538  0.600554   
9976 -0.578736 -0.573809    -0.139979 -1.095988 -0.564665  0.687130  0.431000   
9977 -0.578736 -0.573809     0.335972 -1.095988 -0.660018  1.378686 -1.225848   
9978 -0.578736 -0.573809     1.277529  0.912419  0.102810  1.378686  0.264953   
9979 -0.578736 -0.573809     0.273892 -1.095988  1.819175 -1.387538  0.216958   
9980 -0.578736  1.742740     0.936085  0.912419 -0.373958  0.341352 -0.033888   
9981  1.727904 -0.573809    -1.578181  0.912419  0.293517 -0.695982  1.210909   
9982  1.727904 -0.573809     0.046263 -1.095988  0.674932  0.687130  0.972192   
9983 -0.578736 -0.573809    -0.388302  0.912419  0.102810 -0.350204 -1.225848   
9984  1.727904 -0.573809    -0.502117  0.912419 -0.373958  0.687130  0.226247   
9985 -0.578736 -0.573809     0.087650  0.912419 -0.278604  0.341352  0.758973   
9986  1.727904 -0.573809     0.232504  0.912419  0.770285 -1.387538  1.716402   
9987 -0.578736  1.742740    -0.460730  0.912

In [0]:
from sklearn.model_selection import train_test_split
v_size = 0.30
seed = 0
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=v_size, random_state=seed)

In [0]:
from keras.models import Sequential
from keras.layers import Dense 

classifier = Sequential()
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = "binary_crossentropy", metrics = ['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [0]:
classifier.fit(X_train, Y_train, batch_size = 11, nb_epoch = 20)

Instructions for updating:
Use tf.cast instead.


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/20
7000/7000 [==============================] - 1s 185us/step - loss: 3.7311 - acc: 0.7660
Epoch 2/20
7000/7000 [==============================] - 1s 90us/step - loss: 3.2334 - acc: 0.7966
Epoch 3/20
7000/7000 [==============================] - 1s 88us/step - loss: 3.2419 - acc: 0.7977
Epoch 4/20
7000/7000 [==============================] - 1s 81us/step - loss: 3.0035 - acc: 0.7783
Epoch 5/20
7000/7000 [==============================] - 1s 82us/step - loss: 2.6309 - acc: 0.7977
Epoch 6/20
7000/7000 [==============================] - 1s 82us/step - loss: 2.6070 - acc: 0.7977
Epoch 7/20
7000/7000 [==============================] - 1s 82us/step - loss: 2.5989 - acc: 0.7977
Epoch 8/20
7000/7000 [==============================] - 1s 82us/step - loss: 2.5956 - acc: 0.7977
Epoch 9/20
7000/7000 [==============================] - 1s 83us/step - loss: 2.5943 - acc: 0.7977
Epoch 10/20
7000/7000 [==============================] - 1s 83us/step - loss: 2.5938 - acc: 0.7977
Epoch 11/20
7000/7

In [0]:
Y_pred = classifier.predict(X_test)
Y_pred

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [0]:
Y_pred2 = Y_pred > 0.5
Y_pred2

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [0]:
Yp=  classifier.evaluate(X_test,Y_test)
print(Yp)
print("Accuracy of predicted value: ", Yp[1])

3000/3000 [==============================] - 0s 25us/step
[2.684254176457723, 0.7929999998410543]
Accuracy of predicted value:  0.7929999998410543


In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred2)
print (cm, '\n\n', Y_pred2[:5, :])

[[2379    0]
 [ 621    0]] 

 [[False]
 [False]
 [False]
 [False]
 [False]]


In [0]:
(2379)/(2379+621+0+0)

0.793